image: node:lts

cache:
  paths:
    - node_modules
    - .yarn

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Installing dependencies"
    - yarn install
    - echo "Building application"
    - yarn build

test:
  image:
    # Make sure to update this version number on version update
    name: cypress/included:11.2.0
    entrypoint: ['']
  stage: test
  script:
    - yarn install
    - yarn cypress install
    - echo "Checking format code eslint"
    - yarn eslint .
    - echo "Checking types"
    - yarn tsc --noEmit
    - echo "Running tests"
    - yarn test:ci --browser chrome
